### ISSUE TITLE
Request - Setup with multiple elm.json files using glob patterns

### ISSUE THREAD

**Issue by annaghi** [gulp-elm/gulp-elm#82]
First of all, thank you for this useful package, it saves a lot of time and works well with `browser-sync`!

I would like to configure the build process according to this simplified directory structure:

```
project
│
└───elm
│   │   gulpfile.js
│   │
│   └───samples
│       │
│       └───foo
│       │       elm.json
│       │       index.js
│       │       style.scss
│       │       src/Main.elm
│       │
│       └───bar
│               elm.json
│               index.js
│               style.scss
│               src/Main.elm
|
└───assets
    │
    └───samples
        │
        └───foo
        │       index.js
        │       main.js
        │       style.css
        │
        └───bar
                index.js
                main.js
                style.css
```

❌ This is my attempt to configure `gulp-elm` (the `bundle` function is needed because the Elm code is actually more than a single `Main.elm`):
```js
src('samples/*/src/Main.elm')
    .pipe(elm.bundle('main.js', { cwd: 'samples/*/', debug: true }))
    .pipe(dest('../assets/samples/'))
```

✔️ Processing `scss` files with a similar approach works fine:
```js
 src('samples/*/style.scss', { sourcemaps: true })
    .pipe(sass().on('error', sass.logError))
    .pipe(dest('../assets/samples/', { sourcemaps: true }))
```

✔️ Configuring directories one by one works too, e.g this is the directory `foo` config:
```js
src('samples/foo/src/Main.elm')
    .pipe(elm.bundle('main.js', { cwd: 'samples/foo/', debug: true }))
    .pipe(dest('../assets/samples/foo/'))
```

It seems that using glob patterns in `cwd` is not allowed. Are you willing to support this setup?

**Comment by bdukes** [comment]
I'm not sure that I'd have the context to resolve that `*` in the `cwd` option based on the file.  My initial thought was that we could allow `cwd` to take a function that dynamically resolved the directory, but then I realized that this ultimately resolves to a single call to the `elm` executable, so it really doesn't conceptually make sense to have multiple `cwd` values.

If you were going to compile these files manually with the `elm make` command, what might that look like?

**Comment by annaghi** [comment]
It would look like `elm make src/Main.elm` for each of the samples.

Perhaps some context helps: This is a widget gallery, `foo` and `bar` are independent widgets, each of them is a compact and complete `Browser.element` application. Only one of the widgets (the compiled `main.js` and `style.css`) is used on a PHP site.

This setup helps us to develop these widgets in parallel, we can reuse some shared packages among them, test and build them at once, etc.

**Comment by bdukes** [comment]
Since you're going to need multiple calls to `elm make`, you'll want to _avoid_ `bundle`.  Once you have those output JS files, you'll need to combine them (probably using [gulp-concat](https://www.npmjs.com/package/gulp-concat)).  In that scenario, it _does_ sound like making the `cwd` option take a function would be helpful.  Does that sound like the solution you're looking for?

**Comment by annaghi** [comment]
You are right, I am sorry for the misleading `bundle`. Yes, if I could pass a function to `cwd` that would be great!

**Comment by bdukes** [comment]
Great!  Would you be interested in submitting a pull request to add that functionality?  I'm happy to provide direction and review.  If you're unable to submit a PR, I can tackle it, but it may be a couple of weeks before I can get to it.

**Comment by annaghi** [comment]
I am going to try!

**Comment by annaghi** [comment]
Sorry, I am not going to implement this, started to use WebPack for different reasons.
